### PR TITLE
StyleService: add type attribute detection

### LINKED ISSUE #2131: KML: icon text alignment incorrect
KML with point features are styled with incorrect textAlignment and color properties.

Incorrect: 
image

Should be something like: 
image

### PR DESCRIPTION
**Pull request by thiloSchlemmer**
fixes #2131

### CODE REVIEW

File: src/modules/olMap/services/StyleService.js [hunk 1]
```diff
@@ -87,6 +88,7 @@ export class StyleService {
 			case StyleTypes.MEASURE:
 				this._addMeasureStyle(olFeature, olMap);
 				break;
+			case StyleTypes.ANNOTATION:
```
Comment (taulinger) [inline src/modules/olMap/services/StyleService.js:91]: uncovered by a test

File: src/modules/olMap/services/StyleService.js [hunk 2]
```diff
@@ -263,7 +265,7 @@ export class StyleService {
 				const color = styleColor ? styleColor : iconService.decodeColor(symbolSrc);
 				const scale = markerScaleToKeyword(style.getImage().getScale());
 				const text = style.getText().getText();
-				return { symbolSrc: symbolSrc, color: rgbToHex(color), scale: scale, text: text };
+				return { symbolSrc: symbolSrc, color: rgbToHex(color ? color : style.getText().getFill().getColor()), scale: scale, text: text };
```
Comment (taulinger) [inline src/modules/olMap/services/StyleService.js:268]: partly uncovered by a test

**Comment by taulinger** [comment]
Works nicely for me!

**Review by taulinger — APPROVED** [review]
