### PR TITLE
GeneralFeedback fix wrong i18n key

### LINKED ISSUE #1747: wrong i18n key in feedback form
image

### PR DESCRIPTION
**Pull request by norbertK**
fixed #1747

### CODE REVIEW

File: src/modules/feedback/components/mapFeedback/MapFeedbackPanel.js [hunk 1]
```diff
@@ -219,7 +219,13 @@ export class MapFeedbackPanel extends MvuElement {
 						${translate('feedback_mapFeedback_text_after')}
 					</div>
 					<div class="ba-form-element" id="category-form-element">
-						<select id="category" .value="${mapFeedback.category}" @change="${onCategoryChange}" required>
+						<select
+							id="category"
+							.value="${mapFeedback.category}"
+							@change="${onCategoryChange}"
+							placeholder="${translate('feedback_mapFeedback_categorySelection')}"
```
Comment (thiloSchlemmer) [inline src/modules/feedback/components/mapFeedback/MapFeedbackPanel.js:226]: Unnecessary. The select element does not have a placeholder attribute.

**Review by thiloSchlemmer — APPROVED** [review]
Thx
