### PR TITLE
ElevationProfile now emits error notification

### LINKED ISSUE #1470: ElevationProfile does not fire notification
... when ElevationService throws exception

### PR DESCRIPTION
**Pull request by norbertK**
fixes #1470

### CODE REVIEW

File: src/modules/elevationProfile/components/ElevationProfile.js [hunk 1]
```diff
@@ -423,16 +424,16 @@ export class ElevationProfile extends MvuElement {
...
 			try {
 				const profile = await this._elevationService.getProfile(coordinates);
 				this._enrichProfileData(profile);
 				this.signal(Update_Profile_Data, profile);
 			} catch (e) {
-				console.warn(e.message);
-				// Todo: emit error notification
-				// this.signal(Update_Profile_Data, null);
+				console.error(e);
+				emitNotification(translate('elevationProfile_could_not_load'), LevelTypes.ERROR);
```
Comment (taulinger) [inline src/modules/elevationProfile/components/ElevationProfile.js:436]: The ElevationProfile won't be (fully) opened when an exception occurs (in order to display an "empty" profile). Therefore we have to call also `this.signal(Update_Profile_Data, EmptyProfileData);` for that case.

**Review by taulinger — APPROVED** [review]
Thx
